### ISSUE TITLE
Cannot see the 1.4.0

### ISSUE THREAD

**Issue by JaiSharp** [Seklfreak/discord-image-downloader-go#1]
I've downloaded the exe + the source (just in case) and when I run it I got indeed the config file. I edited it with my username and password. (I just left the path as it is because I am unsure what it really does) saved it and run the tool again.
But then; 
[http://imgur.com/a/whLxp](url)

Edit: I did tryed changing the path but that didn't helped.

**Comment by Seklfreak** [comment]
This is the intended behavior. After the "Client is connected" message it starts to wait for new messages in the configured channels(/paths) containing image links and downloads them until you exit the client.

The channel config is important, you have to specify the channels you want to monitor and where you want the pictures to be saved.

**Comment by JaiSharp** [comment]
Is it possible for you to make a little video, if you don't mind it?

**Comment by Seklfreak** [comment]
No I don't really have the resources to make a video currently, and I don't think it would clear thinks up either, sorry. Are you sure you get what the point of this tool is? What do you expect from the tool? If you want we can chat on Discord (I'm Sekl#7397), it might speed up communication a bit.
