### ISSUE TITLE
 HTTP 400 Bad Request, {"captcha_key": ["captcha-required"]}

### ISSUE THREAD

**Issue by Jake-Watkins** [Seklfreak/discord-image-downloader-go#102]
I don't know if in the past two days this has come up or something but I got this message trying to run it today, 
error creating Discord session, Unable to fetch discord authentication token. HTTP 400 Bad Request, {"captcha_key": ["captcha-required"]}

I'm not sure if discord has required a captcha in the past or if this is new.

**Comment by Jake-Watkins** [comment]
never mind, issue is resolved by first logging into the discord account, the issue must have come up because I am on a new network.

**Comment by Eurocenter** [comment]
Oh dude, i have the same trouble :(
![image](https://user-images.githubusercontent.com/56001992/90570585-6683c380-e186-11ea-9fa8-7f77952db30e.png)

**Comment by drachedachte1** [comment]
> Oh dude, i have the same trouble :(
> ![image](https://user-images.githubusercontent.com/56001992/90570585-6683c380-e186-11ea-9fa8-7f77952db30e.png)
> 

Use the token method 

Join the unofficial support server for help
https://discord.gg/d8MYEC6
