### ISSUE TITLE
"12 Pictures Downloaded"

### ISSUE THREAD

**Issue by lopalop2** [Seklfreak/discord-image-downloader-go#107]
I'd _really_ prefer for my status to not be changed to the amount of pictures I've downloaded, but I can't seem to disable it. Display current game activity is off in Discord, but its just ignoring that in favor of this message.

**Comment by Jake-Watkins** [comment]
I use a second account that I made just for this utility, that way my
friends don't see my status as downloading images

**Comment by lopalop2** [comment]
That is what I'm doing now, but it seems like more of a workaround than a solution.

**Comment by Jake-Watkins** [comment]
In main.go try commenting out the two lines which call updateDiscordStatus()
