### ISSUE TITLE
Download Full Channel History

### ISSUE THREAD

**Issue by tazeps** [Seklfreak/discord-image-downloader-go#111]
Hi,

I didn't understand the part about downloading a full channel history. and I don't really know what's an "interactive channel" or if I need to.

all the instructions in the "readme" were clear except the last portion about this feature.
Where do I enter "history" ? by "bot" what are you referring to ?

I understood that the basic idea is treating the DM as a channel and doing the same steps as downloading from a regular channel. except i don't understand how we can move the whole desired channel's history to the DM between the two accounts.

**Comment by Jake-Watkins** [comment]
You need another account to pm your 'bot' account and then follow the
prompt

**Comment by Jake-Watkins** [comment]
And then the bot will download the files to the location specified in the
config file

**Comment by tazeps** [comment]
I did create another account. and sent a message to it and was able to identify it's "channel ID"
you say "bot account" i'm not sure i understand what that means.

and is the PM supposed to say something particular or just a "hi" is enough ?

**Comment by Jake-Watkins** [comment]
By bot account I mean the account in the config which is downloading all
the files. Your other account will pm the bot account the message 'history'
and then the bot will reply asking for the channel id's

**Comment by tazeps** [comment]
aaah I see ok. I didn't realize this was actually a "bot". It wasn't mentioned anywhere in the introduction. (if it was I missed it)

but yeah I also had to figure out a few more things along the way but now I got it working :) Thanks man!

**Comment by tazeps** [comment]
i'd close the issue but it seems i'm not authorised to. i guess it's just for project owner/co-
