### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by SadhaRoti** [Seklfreak/discord-image-downloader-go#115]
iv configured my config file and i cant get the bot to download anything on my discord...it says 0 pictures download. Im note sure if anything is wrong with my config file..id like to know if anyone can show me an example of this file set up for discord..or can mines by someone that has got this working.

**Comment by SadhaRoti** [comment]
my config file

**Comment by DreamPhreak** [comment]
Remove the email and password lines and replace with token, there are detailed instructions in a different issue on how to get your auth token. Also what's going on with the interactive channels section? I don't think a full link like that works, but if you sent a command to it and it responded with that "0 pictures downloaded" message, i dont even know anymore. Its supposed to be just the channelid to a private channel with your bot and account.
