### ISSUE TITLE
Please make sure the channels have been whitelisted

### ISSUE THREAD

**Issue by kaikun26** [Seklfreak/discord-image-downloader-go#119]
Hello, while trying to download the history of a channel, the bot asked me to send the channel ID, as expected. Then, I send the ID of the channel i want to download, and guess what happenes? It just re-tells me to send the ID. Looked like this>
-history
-Please tell me one or multiple Channel IDs (separated by commas)
Please make sure the channels have been whitelisted before submitting.
-ID
--Please tell me one or multiple Channel IDs (separated by commas)
Please make sure the channels have been whitelisted before submitting.

and so on.
maybe because I didnt whitelist the channels? but how do I do that?

I would like some help....XD

edit: my status changes to: "0 pics downloaded" but nothing happenes.

**Comment by kaikun26** [comment]
Edit>> workde, I just had to add the channel ID in the channel tab.

**Comment by Fury180** [comment]
I have this same issue. What do you mean by add the channel ID to the channel tab??

**Comment by Jake-Watkins** [comment]
he probably means in the config file
