### ISSUE TITLE
=Unable to find valid link

### ISSUE THREAD

**Issue by stickerx** [Seklfreak/discord-image-downloader-go#123]
i do everything rigth but 

respond me  Unable to find valid link

**Comment by Kakkela** [comment]
Please describe your issue better, start by describing what kind of link you are posting to it and show your config file (remove your login information).

**Comment by stickerx** [comment]
`[auth]
token =....


[general]
skip edits                           = true
download tistory sites               = false
max download retries                 = 5
download timeout                     = 60
send notices to interactive channels = false

[channels]
channelid1 = 267292556709068800 C:\Users\Meneow\Desktop\xxx\pick
channelid2 = 498842712490115094 C:\Users\Meneow\Desktop\xxx\pick
channelid3 = 369876416227180555 C:\Users\Meneow\Desktop\xxx\pick

[flickr]
api key = your flickr api key

[twitter]
consumer key        = your consumer key
consumer secret     = your consumer secret
access token        = your access token
access token secret = your access token secret

[interactive channels]
523600647107379201 = C:\Users\Meneow\Desktop\xxx\pick`

**Comment by Kakkela** [comment]
Your channels section is wrong format (though you have interactive channels right) and you didn't say what kind of link you were having problems with. Not all sites are supported.

**Comment by stickerx** [comment]
what is wrong format ?

**Comment by Kakkela** [comment]
> channelid1 = 

is unncessary and = sign should be between ID and Path

**Comment by stickerx** [comment]
Please make sure the channels have been whitelisted before submitting.


please how i can add channels in whitelisted ?

**Comment by Kakkela** [comment]
That [channels] section is the whitelist

**Comment by stickerx** [comment]
where ?

**Comment by stickerx** [comment]
where i can  find  whitelist ?

**Comment by stickerx** [comment]
now i get this when i put id channel 

Please tell me one or multiple Channel IDs (separated by commas)
Please make sure the channels have been whitelisted before submitting.

**Comment by DreamPhreak** [comment]
So instead of having this:
```
[channels]
channelid1 = 267292556709068800 C:\Users\Meneow\Desktop\xxx\pick
channelid2 = 498842712490115094 C:\Users\Meneow\Desktop\xxx\pick
channelid3 = 369876416227180555 C:\Users\Meneow\Desktop\xxx\pick
```

change it to this:
```
[channels]
267292556709068800 = C:\Users\Meneow\Desktop\xxx\pick
498842712490115094 = C:\Users\Meneow\Desktop\xxx\pick
369876416227180555 = C:\Users\Meneow\Desktop\xxx\pick
```

And then when you message your bot in DM, type "history" and then it will ask that question and then give it the channel id from the list above, for example just input "267292556709068800"

**Comment by stickerx** [comment]
Ha! it works now! Thank you for pointing me into the right direction.
