### ISSUE TITLE
Using History?

### ISSUE THREAD

**Issue by HusbandoMax** [Seklfreak/discord-image-downloader-go#13]
Been trying to get this working but every time I send the ID after history I just keep getting the same message "please send me a channel id (from the whitelist)"
It seems to be working fine downloading new posts but is there a way to have it not ask every time for the path and just auto download without posting in the channel?

**Comment by Iksanun** [comment]
Did you make sure you entered in the values correctly?
You should have this in your config
```
[channels]
12134 = C:\Pictures\Channel12134Images
```
Where 12134 is the ID of the channel you want to download from.
The second config file should have :
```
[interactive channels]
4545 = C:\Pictures\Channel12134Images
```
Where 4545 is the ID of your direct message channel conversation between your primary and secondary discord channels, and is different from the channel you want to download from. Make sure you save and restart the .exe.

**Comment by FusDremJun** [comment]
I'm having the same issue and all the values are entered correctly :(

**Comment by FusDremJun** [comment]
[auth]
email    = frsfreerfs
password = fdrgerwfer

[general]
skip edits                           = true
download tistory sites               = false
max download retries                 = 5
download timeout                     = 60
send notices to interactive channels = false

[channels]
247508780319899649 = C:\Users\ciara\Desktop\dis
173460534715219968 = C:\Users\ciara\Desktop\dis
channelid3 = 

[interactive channels]
307565351267467264 = C:\Users\ciara\Desktop\dis

[flickr]
api key = your flickr api key

[twitter]
consumer key        = your consumer key
consumer secret     = your consumer secret
access token        = your access token
access token secret = your access token secret

help would be appreciated :)

**Comment by Seklfreak** [comment]
Thank you very much for your help Iksanun.

@FusDremJun Did you censor the password in the config you just posted? Make it isn't your real password.

And please show me the chatlog with the tool.

**Comment by FusDremJun** [comment]
@Seklfreak yes I did censor my password 

and here's the chat log

![download](https://cloud.githubusercontent.com/assets/25310400/25545942/bd92c3ec-2c58-11e7-9b50-9b2591bb9191.png)

**Comment by Seklfreak** [comment]
you have to send a channel id, not the `history` command again.

**Comment by FusDremJun** [comment]
ah thanks it's working now 👍
