### ISSUE TITLE
Can't download histroy 

### ISSUE THREAD

**Issue by SysAdminSteve** [Seklfreak/discord-image-downloader-go#164]
Hey, Can someone help me download the channel history this is my config

`[auth]
email    = ***@protonmail.com
password = ***

[general]
skip edits                           = true
download tistory sites               = false
max download retries                 = 5
download timeout                     = 60
send notices to interactive channels = false

[channels]
703088344057380*** = C:\Users\***\Downloads

[interactive channels]
703088344057380*** = C:\Users\***\Downloads\history`

I have been PM ing my other account with no response.

Acc1 Today at 1:17 AM
help
history
help
Acc2 Today at 1:25 AM
help
history

**Comment by Vantageright** [comment]
If you head looked at any other issues you would know its broken. Really dude, learn to read.

**Comment by Leavoh** [comment]
I found a work around, When you type "history ChanelID#1, ChannelID#1" it does work! for some reason it just doesn't see the first channelID

**Comment by drachedachte1** [comment]
@SysAdminSteve you ok now? or you still need help?

**Comment by QuantenQuentchen** [comment]
Hey I have the same Issue but sending history ChannelID,SameChannelID doesn't work for me

**Comment by Leavoh** [comment]
Does the bot give you an answer?

not working:
![Discord bot 2](https://user-images.githubusercontent.com/22341463/87785383-594a8080-c838-11ea-8ad6-136e536842ee.PNG)

working:
![Discord bot 1](https://user-images.githubusercontent.com/22341463/87785380-58b1ea00-c838-11ea-856c-4eec2b1c6b83.PNG)

**Comment by drachedachte1** [comment]
alr @Leavoh @QuantenQuentchen 2 options you send screenshots of the config file (censor all data) and send it here or in my alt accs dms
maybenotabot#0013 just add me i will respond asap

**Comment by QuantenQuentchen** [comment]
Sorry I was AFK for about 2 hours.
the Bot doesn't respond at all. But it downloads newly postet images

**Comment by QuantenQuentchen** [comment]
Yeah I know I did that

**Comment by QuantenQuentchen** [comment]
![image](https://user-images.githubusercontent.com/68424527/87798609-84d76600-c84c-11ea-9a27-76219c0c2a04.png)

**Comment by Leavoh** [comment]
there are lots of tutorials, follow those and then apply the history ID,ID to make it work.

**Comment by gurrenm3** [comment]
https://youtu.be/H3R27U7ac5Y
