### ISSUE TITLE
Unable to fetch discord authentication token

### ISSUE THREAD

**Issue by Aspect1103** [Seklfreak/discord-image-downloader-go#168]
I get this error when I go to run this program on my Linux server:

> error creating Discord session, Unable to fetch discord authentication token. HTTP 400 Bad Request, {"captcha_key": ["captcha-required"]}

Do you know why this error is occuring?

**Comment by AiTrat** [comment]
How did you fix this problem? I'm having the same problem now.

**Comment by drachedachte1** [comment]
@AiTrat @Aspect1103 u need to login via discord token bc the program cant solve captchas

Unofficial Support Server
https://discord.gg/d8MYEC6
