### ISSUE TITLE
Too many errors when running on Debian 10

### ISSUE THREAD

**Issue by Aspect1103** [Seklfreak/discord-image-downloader-go#169]
I am trying to run this script on my Linux server, but keep encountering this error:

> command-line-arguments
> ./main.go:68:57: undefined: VERSION
> ./main.go:70:44: undefined: RELEASE_URL
> ./main.go:76:40: undefined: DEFAULT_CONFIG_FILE
> ./main.go:81:16: undefined: DEFAULT_CONFIG_FILE
> ./main.go:119:24: undefined: DATABASE_DIR
> ./main.go:156:8: undefined: initRegex
> ./main.go:223:2: undefined: updateDiscordStatus
> ./main.go:268:20: undefined: getDownloadItemsOfMessage
> ./main.go:300:4: undefined: helpHandler
> ./main.go:302:4: undefined: versionHandler
> ./main.go:302:4: too many errors

Then if I run 'go test', it returns this error:
`[May 11 17:28:38] Found instagram album with 3 images (url: https://www.instagram.com/p/BRiCc0VjULk/?taken-by=gfriendofficial)
[May 11 17:28:39] Found instagram album with 2 images (url: https://www.instagram.com/p/BRhheSPjaQ3/)
--- FAIL: TestGetInstagramUrls (3.25s)
    main_test.go:154: For https://www.instagram.com/p/BHhDAmhAz33/?taken-by=s_sohye, expected map[https://www.instagram.com/p/BHhDAmhAz33/media/?size=l&taken-by=s_sohye:instagram s_sohye - BHhDAmhAz33.jpg], got map[https://www.instagram.com/p/BHhDAmhAz33/media/?size=l&taken-by=s_sohye:instagram N/A - N/A.jpg]
    main_test.go:154: For https://www.instagram.com/p/BHhDAmhAz33/, expected map[https://www.instagram.com/p/BHhDAmhAz33/media/?size=l:instagram s_sohye - BHhDAmhAz33.jpg], got map[https://www.instagram.com/p/BHhDAmhAz33/media/?size=l:instagram N/A - N/A.jpg]
    main_test.go:165: For https://www.instagram.com/p/BL2_ZIHgYTp/?taken-by=s_sohye, expected map[14811404_233311497085396_338650092456116224_n.mp4:instagram s_sohye - BL2_ZIHgYTp.mp4], got map[https://www.instagram.com/p/BL2_ZIHgYTp/media/?size=l&taken-by=s_sohye:instagram N/A - N/A.jpg]
    main_test.go:165: For https://www.instagram.com/p/BL2_ZIHgYTp/, expected map[14811404_233311497085396_338650092456116224_n.mp4:instagram s_sohye - BL2_ZIHgYTp.mp4], got map[https://www.instagram.com/p/BL2_ZIHgYTp/media/?size=l:instagram N/A - N/A.jpg]
http://imgur.com/viZictl
https://imgur.com/viZictl
https://i.imgur.com/viZictl.jpg
http://imgur.com/uYwt2VV
http://i.imgur.com/uYwt2VV.gifv
[May 11 17:28:39] Found imgur album with 7 images (url: http://imgur.com/a/ALTpi)
--- FAIL: TestGetPossibleTistorySiteUrls (3.48s)
    main_test.go:327: For http://soonduck.tistory.com/482, expected map[a: b: c: d: e:], got map[]
    main_test.go:327: For http://soonduck.tistory.com/m/482, expected map[a: b: c: d: e:], got map[]
--- FAIL: TestGetFlickrUrlFromPhotoId (0.28s)
    main_test.go:343: For 31065043320, expected https://farm6.staticflickr.com/5521/31065043320_cd03a9a448_b.jpg, got
--- FAIL: TestGetFlickrPhotoUrls (0.00s)
    main_test.go:379: For https://www.flickr.com/photos/137385017@N08/31065043320/in/album-72157677350305446/, expected <nil>, got invalid flickr api key set
    main_test.go:382: For https://www.flickr.com/photos/137385017@N08/31065043320/in/album-72157677350305446/, expected map[https://farm6.staticflickr.com/5521/31065043320_cd03a9a448_b.jpg:], got map[]
    main_test.go:379: For https://www.flickr.com/photos/137385017@N08/31065043320/in/album-72157677350305446, expected <nil>, got invalid flickr api key set
    main_test.go:382: For https://www.flickr.com/photos/137385017@N08/31065043320/in/album-72157677350305446, expected map[https://farm6.staticflickr.com/5521/31065043320_cd03a9a448_b.jpg:], got map[]
    main_test.go:379: For https://www.flickr.com/photos/137385017@N08/31065043320/, expected <nil>, got invalid flickr api key set
    main_test.go:382: For https://www.flickr.com/photos/137385017@N08/31065043320/, expected map[https://farm6.staticflickr.com/5521/31065043320_cd03a9a448_b.jpg:], got map[]
    main_test.go:379: For https://www.flickr.com/photos/137385017@N08/31065043320, expected <nil>, got invalid flickr api key set
    main_test.go:382: For https://www.flickr.com/photos/137385017@N08/31065043320, expected map[https://farm6.staticflickr.com/5521/31065043320_cd03a9a448_b.jpg:], got map[]
--- FAIL: TestGetFlickrAlbumUrls (0.00s)
    main_test.go:466: For https://www.flickr.com/photos/137385017@N08/albums/72157677350305446/, expected <nil>, got invalid flickr api key set
    main_test.go:469: For https://www.flickr.com/photos/137385017@N08/albums/72157677350305446/, expected map[https://farm6.staticflickr.com/5494/30627074913_b7f810fc26_b.jpg: https://farm6.staticflickr.com/5521/31065043320_cd03a9a448_b.jpg: https://farm6.staticflickr.com/5538/31319458901_088858d7f1_b.jpg: https://farm6.staticflickr.com/5539/31065042720_d76f643b28_b.jpg: https://farm6.staticflickr.com/5600/31065044090_eca63bd5a5_b.jpg: https://farm6.staticflickr.com/5651/31434767515_49f88ee12e_b.jpg: https://farm6.staticflickr.com/5715/30627073573_b86e4b2c22_b.jpg: https://farm6.staticflickr.com/5733/31434764435_350825477e_b.jpg: https://farm6.staticflickr.com/5750/31434766825_529fd08071_b.jpg: https://farm6.staticflickr.com/5758/31289864222_5e3cca7e72_b.jpg: https://farm6.staticflickr.com/5801/30627076673_5a32f3e562_b.jpg: https://farm6.staticflickr.com/5811/31319456971_37c8c4708a_b.jpg: https://farm6.staticflickr.com/5813/31434765285_94b85d5e8c_b.jpg:], got map[]
    main_test.go:466: For https://www.flickr.com/photos/137385017@N08/albums/72157677350305446, expected <nil>, got invalid flickr api key set
    main_test.go:469: For https://www.flickr.com/photos/137385017@N08/albums/72157677350305446, expected map[https://farm6.staticflickr.com/5494/30627074913_b7f810fc26_b.jpg: https://farm6.staticflickr.com/5521/31065043320_cd03a9a448_b.jpg: https://farm6.staticflickr.com/5538/31319458901_088858d7f1_b.jpg: https://farm6.staticflickr.com/5539/31065042720_d76f643b28_b.jpg: https://farm6.staticflickr.com/5600/31065044090_eca63bd5a5_b.jpg: https://farm6.staticflickr.com/5651/31434767515_49f88ee12e_b.jpg: https://farm6.staticflickr.com/5715/30627073573_b86e4b2c22_b.jpg: https://farm6.staticflickr.com/5733/31434764435_350825477e_b.jpg: https://farm6.staticflickr.com/5750/31434766825_529fd08071_b.jpg: https://farm6.staticflickr.com/5758/31289864222_5e3cca7e72_b.jpg: https://farm6.staticflickr.com/5801/30627076673_5a32f3e562_b.jpg: https://farm6.staticflickr.com/5811/31319456971_37c8c4708a_b.jpg: https://farm6.staticflickr.com/5813/31434765285_94b85d5e8c_b.jpg:], got map[]
    main_test.go:466: For https://www.flickr.com/photos/137385017@N08/albums/with/72157677350305446/, expected <nil>, got invalid flickr api key set
    main_test.go:469: For https://www.flickr.com/photos/137385017@N08/albums/with/72157677350305446/, expected map[https://farm6.staticflickr.com/5494/30627074913_b7f810fc26_b.jpg: https://farm6.staticflickr.com/5521/31065043320_cd03a9a448_b.jpg: https://farm6.staticflickr.com/5538/31319458901_088858d7f1_b.jpg: https://farm6.staticflickr.com/5539/31065042720_d76f643b28_b.jpg: https://farm6.staticflickr.com/5600/31065044090_eca63bd5a5_b.jpg: https://farm6.staticflickr.com/5651/31434767515_49f88ee12e_b.jpg: https://farm6.staticflickr.com/5715/30627073573_b86e4b2c22_b.jpg: https://farm6.staticflickr.com/5733/31434764435_350825477e_b.jpg: https://farm6.staticflickr.com/5750/31434766825_529fd08071_b.jpg: https://farm6.staticflickr.com/5758/31289864222_5e3cca7e72_b.jpg: https://farm6.staticflickr.com/5801/30627076673_5a32f3e562_b.jpg: https://farm6.staticflickr.com/5811/31319456971_37c8c4708a_b.jpg: https://farm6.staticflickr.com/5813/31434765285_94b85d5e8c_b.jpg:], got map[]
    main_test.go:466: For https://www.flickr.com/photos/137385017@N08/albums/with/72157677350305446, expected <nil>, got invalid flickr api key set
    main_test.go:469: For https://www.flickr.com/photos/137385017@N08/albums/with/72157677350305446, expected map[https://farm6.staticflickr.com/5494/30627074913_b7f810fc26_b.jpg: https://farm6.staticflickr.com/5521/31065043320_cd03a9a448_b.jpg: https://farm6.staticflickr.com/5538/31319458901_088858d7f1_b.jpg: https://farm6.staticflickr.com/5539/31065042720_d76f643b28_b.jpg: https://farm6.staticflickr.com/5600/31065044090_eca63bd5a5_b.jpg: https://farm6.staticflickr.com/5651/31434767515_49f88ee12e_b.jpg: https://farm6.staticflickr.com/5715/30627073573_b86e4b2c22_b.jpg: https://farm6.staticflickr.com/5733/31434764435_350825477e_b.jpg: https://farm6.staticflickr.com/5750/31434766825_529fd08071_b.jpg: https://farm6.staticflickr.com/5758/31289864222_5e3cca7e72_b.jpg: https://farm6.staticflickr.com/5801/30627076673_5a32f3e562_b.jpg: https://farm6.staticflickr.com/5811/31319456971_37c8c4708a_b.jpg: https://farm6.staticflickr.com/5813/31434765285_94b85d5e8c_b.jpg:], got map[]
FAIL
exit status 1
FAIL    github.com/Seklfreak/discord-image-downloader-go        7.897s`

Please fix this. Thanks!

**Comment by jrl155** [comment]
I got the same errors on my Mac.

**Comment by Aspect1103** [comment]
I solved it by compiling the program into its own executable then running chmod -x (I think) which turns it into an executable. Then I was able to sudo run the program. It's kinda annoying though

**Comment by jrl155** [comment]
> I solved it by compiling the program into its own executable then running chmod -x (I think) which turns it into an executable. Then I was able to sudo run the program. It's kinda annoying though

I tried using 'go build main.go' and it still spits out the errors.

**Comment by Aspect1103** [comment]
Hmm, did you try go fix or reinstalling go?

**Comment by jrl155** [comment]
Same errors still. Oh well
