### ISSUE TITLE
[Feature Request] Support audio files

### ISSUE THREAD

**Issue by realicejoanne** [Seklfreak/discord-image-downloader-go#175]
Hi @Seklfreak, thank you for making this useful bot! I love it.

By the way, I saw this pull request (https://github.com/Seklfreak/discord-image-downloader-go/pull/171) so I think it's possible to make the audio files downloadable too. Can you add this too? Thank you!

**Comment by Seklfreak** [comment]
merged and publishes a new release https://github.com/Seklfreak/discord-image-downloader-go/releases/tag/v1.37
