### ISSUE TITLE
The downloader gives me an error: Missing Access

### ISSUE THREAD

**Issue by Klaus-Schmerz** [Seklfreak/discord-image-downloader-go#178]
after setting up the program, and when I chat the id of the channel, it returns an error
downloading to `M:\discord\pictures`
HTTP 403 Forbidden, {"message":"Missing Access", "code":50001}
done, 0 download links started!
and that folder is still empty 
what should I do?

**Comment by drachedachte1** [comment]
Maybe run the program with administrator or it maybe dosent correctly login?

Join the Unofficial support server: https://discord.gg/8Gw3JQS

**Comment by Klaus-Schmerz** [comment]
Now It give me 'unable to find valid link'...
The downloader successfully logged in with my second account and no errors.

**Comment by Klaus-Schmerz** [comment]
I fixed the problem somehow :D
My primary account have the channel that I want to download the images, and my second account did not.
So I changed the primary and second. config file now have my primary account and I chat to my primary account on my second.
And the problem was disappeared! Thanks to help me @drachedachte1
