### ISSUE TITLE
saving History progress

### ISSUE THREAD

**Issue by drakkillen** [Seklfreak/discord-image-downloader-go#18]
i have a question if that the bot/program keeps track of what images it has downloaded by the use of history. like if you accidently close the program while its running will it pickup were it was interupted or start over?

**Comment by Seklfreak** [comment]
The tool doesn't save the progress but it does save every link downloaded in a database. That means if you restart the downloading process it will go through all messages again but skip the links it already downloaded.

**Comment by drakkillen** [comment]
well that kinda is what i ment with progress, well
i got the anwser thanks :+1: ) really nice program :)

**Comment by Seklfreak** [comment]
Thank you :)
