### ISSUE TITLE
Keeps Closing on me 

### ISSUE THREAD

**Issue by CamZ9878** [Seklfreak/discord-image-downloader-go#19]
I try to run it but it keeps closing on me 
[test.zip](https://github.com/Seklfreak/discord-image-downloader-go/files/874319/test.zip)
That zip contains a video since I couldnt find a suitable place to upload it

**Comment by DreamPhreak** [comment]
Have you done the changes in the config.ini? On first run, the program closes itself to generate the config.ini and files so you can edit them before trying to run the program again. Maybe if you didn't change any settings, might be a possible reason it's closing itself, like for example no channels to watch.

**Comment by CamZ9878** [comment]
Already tried removing the config and it still crashes. Even tried using one that was untouched still didnt work but I'm using an older version and it works just fine.

**Comment by Seklfreak** [comment]
Which version works fine? Are you using Windows 64 Bit?

**Comment by CamZ9878** [comment]
I'm using Windows 10 64 bit yes and I'm using version 1.7.1 I havent tried any of the newer ones other than the most recent one which is the one that kept closing I also tried a few releases before that and they did the same thing. Is it possible that me running it from my flashdrive could some how cause an issue?

**Comment by Seklfreak** [comment]
Does it print an error before it crashes?

I don't think running it from your flash drive causes issues.
