### ISSUE TITLE
No response to history or any other command sent via DM

### ISSUE THREAD

**Issue by Drakonas** [Seklfreak/discord-image-downloader-go#20]
I am using the latest release (1.20.1) as of writing, and I'm not sure what's going on. But I am getting no response when I send the history command via dm even though the program says "Connected as <username>", neither back through my main account DM nor on the command line.

It is also not downloading the images, which is why I am creating an issue.

EDIT: Downloading of new images works. But the history download doesn't because the program isn't responding to DM's sent from my primary account to the secondary account that the image downloader is connected to.

Config:

        [auth]
        email    = xxxxxxxx@xxx.xxx
        password = xxxxxxxx
        
        [general]
        skip edits                           = false
        download tistory sites               = false
        max download retries                 = 5
        download timeout                     = 60
        send notices to interactive channels = false
        
        [interactive channels]
        178723432110751744 = X:\HJS
        
        [flickr]
        api key = your flickr api key
        
        [twitter]
        consumer key        = your consumer key
        consumer secret     = your consumer secret
        access token        = your access token
        access token secret = your access token secret

![Screenshot](http://genesis.whatbox.ca:42424/img/Discord_2017-04-11_17-08-11.png)

**Comment by Drakonas** [comment]
Nevermind I didn't understand the difference between [interactive channels] and [channels]. Kind of confusing on first use lol. interactive channels you have to put the actual DM id as seen by the secondary account (in the URL, not the copied ID with Discord itself), not the server channel ID. lol

**Comment by sajal0limbu** [comment]
How did you solve this? Can you please explain?
