### ISSUE TITLE
when it trys to download picture it says access denied

### ISSUE THREAD

**Issue by ZombieCuber** [Seklfreak/discord-image-downloader-go#203]
when it trys to download picture it says access denied and then it gives up

**Comment by drachedachte1** [comment]
The bot dosent have access to the channel or cant download to the location u set
make sure the bot has access to the channels u wana download from and the folders are accessable

Unofficial image downloader support server
https://discord.gg/d8MYEC6

**Comment by drachedachte1** [comment]
@ZombieCuber any more help?

else check my message above :D

**Comment by ZombieCuber** [comment]
oh I've kind of just given up and forgotten about it so i don't need any
more help


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by drachedachte1** [comment]
lmao
also lol avast is bad use bitdefender
when u dont need any more help please close the issue :D

**Comment by ZombieCuber** [comment]
oh this was my first issue on github so I Didn't know you had to do that
sorry


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
