### ISSUE TITLE
playing : x pictures downloaded

### ISSUE THREAD

**Issue by eylae** [Seklfreak/discord-image-downloader-go#22]
when using your program (wich works really well) i have found everybody can see i am downloading pictures and how many. is there any way to turn it off? (i have disabled game settings, game overlay, rebooted both discord and the .exe to no avail.

thank you for your time. 
![image](https://cloud.githubusercontent.com/assets/28872607/26322107/e03d7c8c-3f29-11e7-870c-9d153846ee33.png)

**Comment by Seklfreak** [comment]
There is no way to turn this off at the moment.

If you don't want it to display on your profile I recommend using the bot with a secondary discord account.

I will keep this issue open and implement a setting to turn it off when I have the time.

**Comment by eylae** [comment]
okay, thank you for responding so quickly, ill see what i can do, its more to bust some people who are uploading and insta removing pictures, so i can at least see them later. 

i will see if i can get a 2nd account rolling in there.

kind regards;

**Comment by Seklfreak** [comment]
Please don't use this tool invade people's privacy.

**Comment by eylae** [comment]
oh no i wont, they just tease us with those pictures, those who see it do, those who didnt yeah. its just i dont want to miss any.

**Comment by Seklfreak** [comment]
I decided that I won't implement that feature, sorry.
