### ISSUE TITLE
[Suggestion] Ability to enter multiple discord channels in the JSON

### ISSUE THREAD

**Issue by PWDSerialgamer07** [Seklfreak/discord-image-downloader-go#224]
For now (I think), you can't set multiple discord channels in the JSON. Like let's say you have 2 channels you wish to download from, you should just be able to put them all at once and separate them with like a comma. Kinda like that:
![image](https://github.com/Seklfreak/discord-image-downloader-go/assets/118306463/d05dc86a-8dcd-4c17-b76c-20187fb391c5)

**Comment by dragonGRaf1312** [comment]
not sure why u doing that in the json u should have a config.ini where u can input all the ids + the destination folder 
doesnt matter how many

**Comment by PWDSerialgamer07** [comment]
oh. i thought I had to put it in the json. Sorry about that
