### ISSUE TITLE
Len out of range. 

### ISSUE THREAD

**Issue by eylae** [Seklfreak/discord-image-downloader-go#25]
Started gitting this error when launching, already tried reload config and redownload tool. 
https://gyazo.com/70a5ca48506f97d1a8543e32a3270fa3

cmd normally closes instantly after promting error lines. but here is a pic of the errors it produces.

kind regards.

**Comment by Seklfreak** [comment]
Which Windows version are you using? 32 bit or 64 bit?

**Comment by Seklfreak** [comment]
Please post your config file.
