### ISSUE TITLE
Downloader randomly stops when processing historical entries

### ISSUE THREAD

**Issue by Jamesl2k5** [Seklfreak/discord-image-downloader-go#26]
The downloader throws this error:
net/http: request canceled (Client.Timeout exceeded while reading body)
while attempting to download previous images.
It occurred once while attempting to download new images, after catching up with a previous run of downloads, and it occurred again while processing already downloaded images.
What causes this error, and what can be done to prevent it?
Or is this a bug?

**Comment by Seklfreak** [comment]
That issue is either your internet having a bad connection or the Discord API having issues. I would suggest trying it at a different time, or with a more stable internet connection.
