### ISSUE TITLE
Clearing Stats and redownloading pictures

### ISSUE THREAD

**Issue by LazDisco** [Seklfreak/discord-image-downloader-go#28]
Hello!

When using your application, I've noticed two minor issues. One, I believe, is connected to the other. The main issue is that if you delete a folder or images that the bot has downloaded, for whatever reason, and then try to go back and redownload those same images, from the same channel, it will simply process them as if they still exist.

Moving on to the second issue, which I believe is attached to the first,  the stats continue to stack up as you download more and more images, with no apparent way to clear them - aside from creating a new account. I am wondering if there are plans to make a change to this.

Thanks for the assistance, great work doing what you do!

**Comment by Seklfreak** [comment]
To reset the Bot please delete the `database` folder created by the Bot.
