### ISSUE TITLE
Add the option to be hidden

### ISSUE THREAD

**Issue by patrickclank9** [Seklfreak/discord-image-downloader-go#29]
Currently, updateDiscordStatus is called, announcing to everyone how many files have been downloaded. Could there be an option to disable this so that an account running the program is indistinguishable from an account that is not?

**Comment by Puffycheeses** [comment]
I Put the .exe in a folder for one of the games in my steam library and it says I'm playing that.

You could also go into settings>Games and then turn off display game.

**Comment by Xanthraxxx** [comment]
As far as best to my knowledge, even turning off the game display setting with obviously no games running and the program running, it will still show the #x amount of images downloaded. Some servers are okay with it, others are weird about it even if we already can download any image manually. :/

**Comment by Seklfreak** [comment]
Hiding the game status is not an option and won't be added by me. If you don't want the game status to appear on your account I recommend creating a second account for the bot.
