### ISSUE TITLE
Requesting 100 more messages, (before 2017-08-11 13:56:10.587 +0000 +0000)

### ISSUE THREAD

**Issue by TLI1233** [Seklfreak/discord-image-downloader-go#31]
What is this : Requesting 100 more messages, (before 2017-08-11 13:56:10.587 +0000 +0000)
EDIT: Also, how to blacklist someone?

**Comment by Puffycheeses** [comment]
This issue seems to be when your downloading history of a channel you have already downloaded the history of before. Its just looking for new messages. This means its either trawling through messages you have already gotten to get to older ones OR its got everything (I think)

**Comment by Seklfreak** [comment]
That's just the bot telling you it's requesting more messages from the API. Blacklisting users is a planned features: #17 .
