### ISSUE TITLE
corrupted GIFs

### ISSUE THREAD

**Issue by Cronosus** [Seklfreak/discord-image-downloader-go#34]
found problem
when program download gifs, then download just jpg image of this gif, not full gif.

**Comment by Seklfreak** [comment]
example url for a gif? gif's work fine for me

**Comment by Cronosus** [comment]
example files cannot be uploaded anywhere, because are corrupted.
but it looks like partially downloaded file, sometimes it shows only part of one image, sometimes just blinking animation.

**Comment by Cronosus** [comment]
ad. little question: max channels is 3, or maximum is not defined?
maybe are files corrupted, because i have added 35 channels

**Comment by Seklfreak** [comment]
There is no channel limit, the bot is working fine with over 200 channels, and downloads huge gifs without any issues. The issue is probably your internet. There is nothing else I can't do without example URLs.
