### ISSUE TITLE
bot not responding to DM's

### ISSUE THREAD

**Issue by sirweeb** [Seklfreak/discord-image-downloader-go#35]
i have tried everything but the bot doesn't respond to any DM's
![untitled](https://user-images.githubusercontent.com/32219543/30772726-ff04bd76-a061-11e7-80fb-a0215bd04dbc.png)
![untitled02](https://user-images.githubusercontent.com/32219543/30772757-af5b62ba-a062-11e7-9bf4-267c43bde140.png)

**Comment by DreamPhreak** [comment]
Make sure you take out those brackets (<>) under interactive channels.

**Comment by sirweeb** [comment]
that fixed it thx
