### ISSUE TITLE
is there a way to stay hidden(when i set it manually)/stop showing X messages downloaded in the playing status?

### ISSUE THREAD

**Issue by DrakeTDL** [Seklfreak/discord-image-downloader-go#36]
titles says it all.
if there is not a way, can you implement it?
that would bring my rating (if there is one) from a 4 to a 5
P.S. what is tistory?

**Comment by Seklfreak** [comment]
There is no way, and I don't plan to add one. If you don't want the status on your main account I recommend creating a second account for the Bot. 

Tistory is a korean blogging site, like blogger.com for example. :)
