### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by DraGoran** [Seklfreak/discord-image-downloader-go#37]
following happened today

![sfdss](https://user-images.githubusercontent.com/17236196/31049460-ceee68f8-a633-11e7-94b0-77fa9725febe.png)

any solution. it closes automaticly atfer start

it happened inbetween a download session

**Comment by Seklfreak** [comment]
Looks like your Database got corrupted, deleting the `database` folder should fix the issue.

**Comment by DraGoran** [comment]
thank you worked : 3
