### ISSUE TITLE
Just closes itself in new version

### ISSUE THREAD

**Issue by Awooooo** [Seklfreak/discord-image-downloader-go#38]
Had a previous version that worked fine but something was pushed out that auto-closed it and forced me to come and download a new version.

New version doesn't load up. Automatically closes itself after a few seconds.

Original version was created on 10/08/2017 and running perfectly until the forced update, I'd tell you the version but I can't seem to find it written in the files anywhere. 

I wish I could provide more detail than this, we have a huge server and this was a critical component of uploading all images on the server to an external website.

**Comment by Seklfreak** [comment]
Updates aren't forced, it's simply a notification.

The new version seems to have trouble with the database sometimes, I had no time to look into it yet. A simple workaround is just to delete the `database` folder to generate a new database. That should fix you issue.
