### ISSUE TITLE
Downloading

### ISSUE THREAD

**Issue by SLASHLogin** [Seklfreak/discord-image-downloader-go#39]
I configured everything, id of channels, path, etc. But when executing program nothing happened. I was trying about few days. Finally I noticed that program has downloaded only 3 pics. But I'm sure that there's mores photos tagged as unseen so I'm not sure what this program is for. I thought this program downloads every photo which one is posted, sent etc on channel and I just turn on program it download all what I missed in the mean time and that's good, but know I suspect that maybe it download only photos which one are posted at time of program's working time.

P.S. I hope that this program do what I thought at first time, if yes, then I worship you for your job.

**Comment by DrakeTDL** [comment]
if you want to download the channels history than you'd want to setup an interactive channel

**Comment by DreamPhreak** [comment]
By default the program will download photos automatically from when it's first running, like you suspected. If you want to download the entire _history_ of images, you have to set up the "interactive channels" option which isn't included in the default config.

You do this by going to the config, adding new lines at the bottom and adding 
`[interactive channels]
<your channel id> = <some valid path>`
(no brackets)

For "your channel id", you have to use a 2nd discord account and send a message to your bot using your browser (https://discordapp.com/channels/@me), and after messaging, you will get a private chat with the bot with the url like (https://discordapp.com/channels/@me/00000000000000000), and that's the channel id at the end. "Some valid path" is just any path on your computer. In the end it should look like
`[interactive channels]
000000000000000000 = C:\users\blah\blah`

Now that it's been set up and the bot has been restarted to recognize those new lines, go back to it's private message channel and type "history" and enter. Then get and send the channel ID for the channel history you want to download.

**Comment by SLASHLogin** [comment]
Uh, after few seconds it makes sense. Anyway I will be needing delete copy of already downloaded manually by me images, so it can be a little bit of work.

**Comment by SLASHLogin** [comment]
Anyway, thank you so much and thanks to developer for work.

**Comment by DreamPhreak** [comment]
You shouldn't have to delete images already downloaded because it records what it downloaded in it's database file to prevent downloading same image twice. If you're going to manually delete images, then be sure to delete the database so you can download those images again, otherwise they will be ignored.

**Comment by SLASHLogin** [comment]
Where do I can find that database?

**Comment by DreamPhreak** [comment]
In the same directory the program is ran from, there should be a folder called "database"

**Comment by SLASHLogin** [comment]
But there's no line about files which one I downloaded earlier manually

**Comment by SLASHLogin** [comment]
Ok I dealt with it. Thank you for your help.
