### ISSUE TITLE
xurls error

### ISSUE THREAD

**Issue by sxnfxsed** [Seklfreak/discord-image-downloader-go#43]
Hi Im running this from the source "go main.go" and the console spits out an error and I'm not sure what to do.

.\main.go:482:28: xurls.Strict.FindAllString undefined (type func() *regexp.Regexp has no field or method FindAllString)
.\main.go:657:35: xurls.Strict.FindAllString undefined (type func() *regexp.Regexp has no field or method FindAllString)
.\main.go:724:31: xurls.Strict.FindAllString undefined (type func() *regexp.Regexp has no field or method FindAllString)

I did a fresh os reinstall and now this happens. It used to run fine before but it's the first time i get this error. I installed the same things as before, maybe I'm missing something. Im not a developer so I dont know where to start with this. Let me know if I can provide more info. Thanks

**Comment by SLASHLogin** [comment]
I think as it's file made to "cooporate" with other files it should work only when you download all files in .exe (that's only my opinion)

**Comment by DrakeTDL** [comment]
I'm also getting the same error while trying to build. my current compromise is that i deleted all the lines with the word "xurls". Now my question is will that mess up the bot in someway, shape, or form?

**Comment by EvilWalks** [comment]
@DrakeTDL thanks for your help with the initial issue I posted about in another thread. No that I've sorted that out, I'm getting the same errors as above. 

Did you manage to find a solution, or can confirm bot functioning fine with the lines you removed?

**Comment by DrakeTDL** [comment]
I found out that the lines that I removed broke the ability to use interactive channels, other than that the bot seems to be functioning fine.

**Comment by EvilWalks** [comment]
@DrakeTDL Ok thanks, I'll give that a shot later on (unless you're interested in sharing your edited main.go somewhere). 

It's a shame there isn't a config option to disable "now playing" update functionality.

**Comment by DrakeTDL** [comment]
The lines that I specifically deleted are in this [Pastebin](https://pastebin.com/eQQ3Y8wK)

**Comment by Seklfreak** [comment]
fixed in d94c23c7db86baa7e66d41ddc91877ebdf05c4c9

**Comment by Rouskuh** [comment]
It's still broken

**Comment by OrIOg** [comment]
Replace 'xurls.Strict.FindAllString'
by         'xurls.Strict().FindAllString'
