### ISSUE TITLE
Can't get response from bot through @dm

### ISSUE THREAD

**Issue by quack15948** [Seklfreak/discord-image-downloader-go#46]
Hello, just wondering if I'm doing something wrong. I've configured the conf.ini file and have this https://puu.sh/yoHPU/634e9bd9e6.png yet I can't get any kind of response from the bot. Thanks a lot for your hard work on this, this is going to save me a ton of right clicking

**Comment by Kakkela** [comment]
`
[interactive channels]
XXXXXXXXXXXXXX = path\to\folder
`
You have set up this part too?

**Comment by DreamPhreak** [comment]
Check this out for instructions for setting up interactive channels to be able to control it through DMs https://github.com/Seklfreak/discord-image-downloader-go/issues/15#issuecomment-302890901

**Comment by quack15948** [comment]
That did it guys. Thanks so much. I read that comment, but I thought [interactive channels] was the same as [channels] in config. I feel dumb
