### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by puppyisodd** [Seklfreak/discord-image-downloader-go#48]
If I turn off the bot for a day then opened it, how can I download all the images posted within that day using the bot assuming i already downloaded everything before that?

**Comment by DrakeTDL** [comment]
you can use the interactive channel to download everything from said day.

**Comment by puppyisodd** [comment]
Ah I see. So, I have to use the interactive channel every time I miss something? Alright. Thank you.

**Comment by Seklfreak** [comment]
Yes, there are currently no recover features or similar.
