### ISSUE TITLE
Suddenly broke?

### ISSUE THREAD

**Issue by RecklessJames** [Seklfreak/discord-image-downloader-go#50]
So yeah I just edited the config file today to add a channel, been using this for a month now.  And then as soon as I did that it no longer works... even when reverting back.  It says an error that I cant read and it crashes right after.

Edit: I managed to grab a screen before it closes...
![c04c38a0bac5bd68677d23c7eaf2fa6d](https://user-images.githubusercontent.com/12752293/33666793-0f32cb3e-da69-11e7-9500-adeb86b85b62.png)

**Comment by DreamPhreak** [comment]
Remove the < > brackets.

**Comment by RecklessJames** [comment]
There aren't any of those in there... and there never were in the first place, but alright here is my config file lol...

https://gist.github.com/RecklessJames/c90c66d1bcb90ce950d5d392063bd9f2

**Comment by DreamPhreak** [comment]
Your config is perfect. I did some searching around and also tested it myself. This isn't your fault at all, it's something else but I'm not 100% sure exactly where its coming from.

My first guess was something else like twitter api having some problems, but it seems fine. Now my guess is that maybe Discord changed something recently that broke the script.

**Comment by Kakkela** [comment]
That last one sounds like too many failed attempts to log into discord and then it wanting to use captcha. My bot starts currently just fine.

Could you have changed the encoding of the file and caused some special character to go wonky in your email or password.

**Comment by RecklessJames** [comment]
Definitely not, and to make sure I reverted a previous version of the file. It is exactly the same as before, also I'm able to log on just fine using the account.  So I have no idea...

**Comment by RecklessJames** [comment]
Okay well I was able to finally get it to work by replacing the login with the account token instead... which is strange cause I didn't have to before but w/e now it works.  Thanks for the help!

**Comment by RecklessJames** [comment]
Updated and bot broke once again... its extremely annoying and frustrating to even _know_ what the issue is when it flashes before my eyes for a split 2nd and it takes an hour to manage to time a screenshot... all I know is that I think its similar to this person's issue judging by the glimpses I can see: https://github.com/Seklfreak/discord-image-downloader-go/issues/51

Which would make no sense considering its been working perfectly fine until now. I don't touch my settings the only times things go wrong is when it updates, lol... so hopefully someone can help out with me (again).

**Comment by Kakkela** [comment]
Can't comment on the problem itself right now, but to avoid future headache with Screenshot you can start the command prompt first and then run the program from there so it won't close on crash.

**Comment by DreamPhreak** [comment]
The problem might have something to do with the database? Maybe try running the program in a new folder to let it create a new database to test if that works. Don't delete the original database folders yet just in case I'm wrong and that's not the source of the problem.

(github.com/HouzuoGuo/tiedot is a "NoSQL database")

**Comment by RecklessJames** [comment]
Tried that, didn't work sadly...
