### ISSUE TITLE
Can't run script on bot account

### ISSUE THREAD

**Issue by aepic999** [Seklfreak/discord-image-downloader-go#51]
So, I've been trying to get the script running on a bot account.
My config.ini file is:
`[auth]
token = [Bot Token]

[general]
skip edits                           = true
download tistory sites               = false
max download retries                 = 5
download timeout                     = 60
send notices to interactive channels = true
[channels]
352049966983806986 = C:\Software Collection\grammar\img
[interactive channels] 
352049966983806986 = C:\Software Collection\grammar\img`

I get this when I try to run the exe with this config:
`discord-image-downloader-go version 1.25.1
error obtaining account details, HTTP 401 Unauthorized, {"code": 0, "message": "401: Unauthorized"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6c12c9]

goroutine 1 [running]:
main.main()
        /home/travis/gopath/src/github.com/Seklfreak/discord-image-downloader-go/main.go:306 +0x1849`

I try sending "history" to the account, and I get no response.
Is there any way to fix this?

**Comment by DrakeTDL** [comment]
I'm assuming your trying to use the bot token from Discordapp.com/developers, if so thats not the token your suppose use. 
To get the your user token you need to do either in the browser or the client: Ctrl + Shift + I -> Application -> Local Storage -> https://discordapp.com -> token

**Comment by aepic999** [comment]
Why do you have to use a user account? Why does it not work right with bot tokens?

**Comment by DrakeTDL** [comment]
Because this tool was made to be used with a user account not a bot account

**Comment by Seklfreak** [comment]
Try putting a `Bot` in front of the token. Example: `Bot xawidaiwj`. Maybe it will work then.

If it doesn't, then this tool is incompatible with bot accounts. It is meant to be run with User Accounts, Bot Accounts have a few different access levels.

**Comment by DreamPhreak** [comment]
Tried and `Bot` in front of the token code, unfortunately doesn't work.

**Comment by Seklfreak** [comment]
Ah, I see, then Bots are sadly not supported by this tool. Thank you for testing it!
