### ISSUE TITLE
Cant run

### ISSUE THREAD

**Issue by Cronosus** [Seklfreak/discord-image-downloader-go#52]
hello
when i try to run, it says Malformed version....
it not makes log and it slosed too fast to full read.
yesterday it works for me
in config all default, just my login credentials added + some channels
i'm not using two-factor authentication

ad. i tried to make screenshot :D 
http://cronos.wz.cz/screen.png

**Comment by DreamPhreak** [comment]
It seems they changed it to where now you need a token regardless if using two-factor auth or not.

Fix: Under the [auth] section, delete both the email/password lines, and replace with
`token = <token key here>`

**Comment by Cronosus** [comment]
thanks for images, it works now

**Comment by revi** [comment]
Btw, getting token via LocalStorage should work on discord client, too.
