### ISSUE TITLE
bot messages

### ISSUE THREAD

**Issue by Cronosus** [Seklfreak/discord-image-downloader-go#53]
Looks like, it not downloading images posted by bots
example from Tatsumaki

images posted by users are downloaded, from the same channel where posting Tatsumaki

**Comment by Seklfreak** [comment]
The script is not ignoring Bot posts, I use it every day to download Bot posts. Looks like the issue lies somewhere else.

**Comment by Kakkela** [comment]
Mind giving examples of such image posts?

**Comment by Cronosus** [comment]
for some reason uploading here not works for me
http://cronos.wz.cz/example.png

**Comment by Kakkela** [comment]
That message has (edited) in the end, is the image link in message before edit?
If it isn't do you have downloading edited messages enabled in your config?

**Comment by Cronosus** [comment]
ist posted like that, it bot does self, not edited manually

**Comment by Cronosus** [comment]
i tried this skip edits disable, but still not downloading these images

**Comment by Seklfreak** [comment]
looks like the bot is not posting a valid link (`http:https://`), that's out of our reach sorry
