### ISSUE TITLE
Imgur direct links result in duplicates

### ISSUE THREAD

**Issue by Kakkela** [Seklfreak/discord-image-downloader-go#60]
```
[Jan 24 20:37:40] Saved URL https://i.imgur.com/O92BEOB.png to D:\kpics\Tunkkausta\tunkkaus\O92BEOB.png from #general/SnekCord

https://imgur.com/O92BEOB

[Jan 24 20:37:41] Saved URL https://imgur.com/download/O92BEOB to D:\kpics\Tunkkausta\tunkkaus\O92BEOB - Imgur.png from #general/SnekCord
```
This link gets posted to channel once (https://i.imgur.com/O92BEOB.png) and it result's in two downloads and above output in log.
If the link is gallery link (https://imgur.com/O92BEOB) no duplicate pictures are saved.

**Comment by Seklfreak** [comment]
fixed in 96df9afbfbf4e0b3014c03b280e24dcb4cd9f506
