### ISSUE TITLE
bot not sending replys in dm

### ISSUE THREAD

**Issue by Nyt3lit3** [Seklfreak/discord-image-downloader-go#61]
i've set everything up correctly. when i run the exe it says that the client is connected

**Comment by Puffycheeses** [comment]
I am having this same issue I hope that this gets fixed as this is the only good image scraper

**Comment by Seklfreak** [comment]
You probably did not set up the interactive channel ID correctly, please follow the instructions here https://github.com/Seklfreak/discord-image-downloader-go/issues/15#issuecomment-302890901
