### ISSUE TITLE
Imgur Gallery Download Doesn't Work

### ISSUE THREAD

**Issue by SalamanderSandwich** [Seklfreak/discord-image-downloader-go#64]
If something like this https://imgur.com/gallery/RtwKw is posted I'm just getting "No image or video found at https://imgur.com/gallery/RtwKw". Tried building from source (ran into an issue with xurls) and still have the same problem.
Lastest version, windows 10.

**Comment by Kakkela** [comment]
Yeah can confirm, imgur URLs in that form won't work. 
Hopefully Sekl fixes this soon now that someone brought it up.

**Comment by Seklfreak** [comment]
fixed in 8f8446a3c9cd2db5b54ffd6bd588bd5bc40d1444, thank you for bringing it to my attention
