### ISSUE TITLE
detailed tutorial please

### ISSUE THREAD

**Issue by XxCHURCH85xX** [Seklfreak/discord-image-downloader-go#67]
can someone please make a quick video showing exactly what values need to be changed in the discord image-gownloader-go.ini file for both downloading pics from multiple threads as well as the history of threads? the super basic "instructions" on the page are not clear at all for beginners like myself.

**Comment by DreamPhreak** [comment]
Well I wrote this a while back and it helped out a few people: https://github.com/Seklfreak/discord-image-downloader-go/issues/15#issuecomment-302890901

**Comment by SLASHLogin** [comment]
I'm not very likely to make video, but I'm likely to make easier to understand version of instructions and what you should keep eye on etc.

**Comment by effektgamer218** [comment]
hey im still having problems with this. how do I use it. or enable it. hope this isnt an inconvenience
