### ISSUE TITLE
Windows cant run this app check publisher for a compatale version

### ISSUE THREAD

**Issue by thunderstorm91** [Seklfreak/discord-image-downloader-go#68]
i have download the new version and i have tried all the combatiblity settings i am running windows 10

**Comment by Kakkela** [comment]
You shouldn't need any compatibility settings to run this on Windows 10, could you give bit more detailed information about your hardware?

**Comment by thunderstorm91** [comment]
i think it maybe that its 32 bit ma be the issue

**Comment by Seklfreak** [comment]
Yes, this tool doesn't support 32 bit windows, sorry.
