### ISSUE TITLE
No response in DM?

### ISSUE THREAD

**Issue by Noneofyabuisness** [Seklfreak/discord-image-downloader-go#72]
I think I've done everything right. I have the channel id in the config for the channel im trying to download as well as my DM, it says client is connected, https://imgur.com/a/VYPLM is my config settings.  I've messaged my logged in account with my other alt account and said history to the logged in account as well as help but no response. Am I doing something wrong?

**Comment by Kakkela** [comment]
Firstly you should remove the token before you post config here.

>

**Comment by Noneofyabuisness** [comment]
my bad, fixed that

**Comment by Noneofyabuisness** [comment]
how do I get it to work though?

**Comment by Seklfreak** [comment]
You probably set up the wrong channel ID. Please follow the instructions here https://github.com/Seklfreak/discord-image-downloader-go/issues/15#issuecomment-302890901
