### ISSUE TITLE
Ability to appear offline?

### ISSUE THREAD

**Issue by JamesSampsan** [Seklfreak/discord-image-downloader-go#73]
Some servers I've joined have begun purging users who are on all the time not contributing. Besides what a stupid fucking point that is, I've already been purged once from a server and don't want it to happen again. 

Is there a way to appear offline and hide the "700 pictures downloaded" in the "Now playing" section? 

Thanks -

**Comment by DreamPhreak** [comment]
For the appear offline, you can log into discord with the account you are using for this, on the bottom left click your picture and you can appear as invisible: 
![](https://i.imgur.com/VvwkJTT.png)

My fork has the option to hide the downloaded status.

**Comment by JamesSampsan** [comment]
Sorry for being a retard, but how do I go about downloading your forked version?

**Comment by DreamPhreak** [comment]
https://github.com/DreamPhreak/discord-image-downloader-go/releases
