### ISSUE TITLE
error 403ing - what did i do wrong?

### ISSUE THREAD

**Issue by artificialSyntax** [Seklfreak/discord-image-downloader-go#75]
I believe I've set everything up correctly, but whenever I give a whitelisted channel id i get this message:

HTTP 403 Forbidden, {"code": 50001, "message": "Missing Access"}
done, 0 download links started!

**Comment by Seklfreak** [comment]
The account you are using does not have access to the given channel. Please ensure the account can see the channel you want it to download.
