### ISSUE TITLE
Help me please.

### ISSUE THREAD

**Issue by CyanRozen** [Seklfreak/discord-image-downloader-go#77]
I'm still having issues at the beginning can someone help me. I did everything DreamPhreak said but it's not working.

**Comment by SLASHLogin** [comment]
Explain your problem and than we can help

**Comment by CyanRozen** [comment]
Ok when I do everything that DreamPhreak has stated. I end up with a command prompt that just shows that it did connect to my discord account, but thats about all it does nothing more and no downloads.

**Comment by Kakkela** [comment]
Could you show us your config file, just remove all the login details and tokens from it before you post it.

**Comment by Seklfreak** [comment]
The tool only downloads links posted while the tool is running by default. Please ensure someone is posting links in the Channel 406… while your tool is running.

Feel free to reopen the issue should this not fix the issue.
