### ISSUE TITLE
2 Steps Auth

### ISSUE THREAD

**Issue by marcussacana** [Seklfreak/discord-image-downloader-go#78]
Support the discord 2 Steps Auth? if yes, how?

**Comment by Seklfreak** [comment]
From the README.md

"In case you are using two-factor authentication you have to login using your token. Remove the email and password lines under the auth section in the config file and instead put in `token = <your token>`. You can acquire your token from the developer tools in your browser (`localStorage.token`) or discord client (Control+Shift+I (Windows) or Command+Option+I, click Application, click Local Storage, click `https://discordapp.com`, and find "token" and paste the value)."
