### ISSUE TITLE
App Just Shuts Down!

### ISSUE THREAD

**Issue by KaleyMoro** [Seklfreak/discord-image-downloader-go#80]
When I opened the app it is running for a moment after few seconds when it has to say" the client is connected to ______" it is closed. I'm on latest release. is this a bug?

**Comment by Kakkela** [comment]
Could you start the program from command line / power shell to see if there's any errors?

**Comment by KaleyMoro** [comment]
I ran the program from command line , it didn't show any erros but it's still acting the same way!.
should i delete my config and start a new one?

**Comment by KaleyMoro** [comment]
I deleted my old config and started the program but it's shutting down in the same way it did earlier

**Comment by Seklfreak** [comment]
I improved the shutdown logic in 3302de7f948e43cbde51149424084dbecc920545, and will push a release later. Might fix it, if not please reopen the issue.
