### ISSUE TITLE
When running the app, Discord shows me online and using an image downloader

### ISSUE THREAD

**Issue by JuanMalusco** [Seklfreak/discord-image-downloader-go#82]
Is there a way you can make the user still appear as offline to other people? 
Because whenever I have the application running, not only can't I no longer appear as offline with discord open, but it also shows the amount of images that have been downloaded as the name of the application I'm running. The thing is, I don't want either of them.
I want to remain offline and like I'm not playing anything or running any app.
Is that functionality already possible? If yes, please tell me how, if not, I'd really appreciate it if you added it.

I've attached a screenshot comparing what I see versus what other users see, when I'm running the application.

Thanks in advance.

![discord_img_downloader](https://user-images.githubusercontent.com/22934944/40155446-b2bcd050-598b-11e8-9e34-ff92a6cdbe76.png)

**Comment by Rouskuh** [comment]
I would love to have an option in the settings to remove the "* pictures downloaded" text.

**Comment by Kakkela** [comment]
Author of this tool has decided to not allow hiding it for transparency reasons towards other users on servers you use this on, but there is fork that has these supports added.

It might not be up to date on other stuff and all the problems you face with it should be directed to that repo.
https://github.com/DreamPhreak/discord-image-downloader-go/releases

**Comment by JuanMalusco** [comment]
Ohhh okay, that's fair, thanks for the info @Kakkela 👍
