### ISSUE TITLE
add support for new tistory urls

### ISSUE THREAD

**Issue by Seklfreak** [Seklfreak/discord-image-downloader-go#89]
`https://t1.daumcdn.net/cfile/tistory/99B6BA355B0F829D02`
=>
`https://t1.daumcdn.net/cfile/tistory/99B6BA355B0F829D02?original`

**Comment by Kakkela** [comment]
Right now bot doesnt download ?original image even if it is linked as such.

**Comment by Seklfreak** [comment]
completed in https://github.com/Seklfreak/discord-image-downloader-go/releases/tag/v1.33
