### ISSUE TITLE
Feature req: editing discord status

### ISSUE THREAD

**Issue by smokeofc** [Seklfreak/discord-image-downloader-go#94]
Is it possible to add the feature to disable and/or edit the **playing x images downloaded** while the selfbot is active?

**Comment by Rouskuh** [comment]
No, you need to use some fork

**Comment by smokeofc** [comment]
it's so easy to add though =/
fixed it for myself, but thought that'd be rather easy to add here =/
```
func updateDiscordStatus() {
	if len(discordstatuscfg) > 0 { 
		dg.UpdateStatus(0, fmt.Sprintf(discordstatuscfg))
	} else {
		dg.UpdateStatus(0, fmt.Sprintf("%d pictures downloaded", countDownloadedImages()))
	}
}
```
and add a field in the ini part allowing for user editing...

**Comment by Kakkela** [comment]
Downloading images from discord channels without people there knowing can be malicious so that kinda feature wont be added. It's been discussed before.
