### ISSUE TITLE
Captcha still stops connection

### ISSUE THREAD

**Issue by Markgarr** [Seklfreak/discord-image-downloader-go#96]
I got the error that a captcha stopped the connection, so I logged in using a browser to clear it. Same machine, same account, but no dice.

**Comment by Markgarr** [comment]
I just tried signing in a few times with both of my accounts and it seems like Discord is being really aggressive with Captchas (Out of 10 trials, all had some kind of Captcha and at least half were puzzles).

**Comment by lexex192** [comment]
Having the same problem...

**Comment by smokeofc** [comment]
Having the same problem... Works if using token though

**Comment by Markgarr** [comment]
Adding 2FA worked!
