### ISSUE TITLE
Instagram posts not downloading consistently

### ISSUE THREAD

**Issue by Kakkela** [Seklfreak/discord-image-downloader-go#97]
Sometimes bot tries to add 
> ?efg=eyJ1cmxnZW4iOiJ1cmxnZW5fZnJvbV9pZyJ9

at the end of the filename and that causes the save to fail on some operating systems.

> [Jul  5 11:37:19] Found instagram album with 3 images (url: https://www.instagram.com/p/Bk1_CuFF6uY/)
> ...
> Error while writing to disk https://scontent-arn2-1.cdninstagram.com/vp/df1c5fbf42dea0751126672da80c3d0a/5BC5AED7/t51.2885-15/e35/36149075_452328475177676_3512995919110864896_n.jpg?efg=eyJ1cmxnZW4iOiJ1cmxnZW5fZnJvbV9pZyJ9 - open X:\X\instagram nayeonk96 - Bk1_CuFF6uY 1.jpg?efg=eyJ1cmxnZW4iOiJ1cmxnZW5fZnJvbV9pZyJ9: The filename, directory name, or volume label syntax is incorrect.
> Gave up on downloading https://scontent-arn2-1.cdninstagram.com/vp/df1c5fbf42dea0751126672da80c3d0a/5BC5AED7/t51.2885-15/e35/36149075_452328475177676_3512995919110864896_n.jpg?efg=eyJ1cmxnZW4iOiJ1cmxnZW5fZnJvbV9pZyJ9

**Comment by Seklfreak** [comment]
fied in 6de46b4ea3afbcec3bdc83242ffba73faa0c52ae and 4ebcabfa44bb3989eb7b8918f546e1587fc46e66
